CREATE TABLE `games` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text NOT NULL,
	`platform` text NOT NULL,
	`language` text DEFAULT 'English' NOT NULL,
	`genre` text,
	`developer` text,
	`publisher` text,
	`release_year` integer,
	`cover_art_url` text,
	`igdb_id` integer,
	`personal_rating` integer,
	`completion_status` text DEFAULT 'unplayed' NOT NULL,
	`hltb_main_story` integer,
	`hltb_extras` integer,
	`hltb_completionist` integer,
	`notes` text,
	`ownership_status` text NOT NULL,
	`condition` text,
	`purchase_price` real,
	`purchase_date` text,
	`purchase_location` text,
	`target_price` real,
	`backlog_position` integer,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL
);
